version: '2.2'

services:

  ### Caddy Server Container
  caddy:
    image: laradock/caddy:local.${CADDY_TAG}
    build: ${CADDY_BUILD_PATH}
    volumes_from:
      - applications
    volumes:
      - ${CADDY_CUSTOM_CADDYFILE}:/etc/Caddyfile
      - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
      - ${DATA_SAVE_PATH}/caddy:/root/.caddy
    ports:
      - "${CADDY_HOST_HTTP_PORT:-80}:80"
      - "${CADDY_HOST_HTTPS_PORT:-443}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

volumes:
  caddy:
    driver: "local"
