version: '2'

services:

  ### Mailhog Container
  mailhog:
    image: laradock/mailhog:local.${MAILHOG_TAG}
    build: ${BUILD_ROOT}/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - frontend
      - backend
