#!/bin/bash
#
# Laradock Shell CLI
#

readonly LARADOCK_CLI="$(basename "$BASH_SOURCE")"
readonly CLI_PATH="$(cd "$(dirname "$(readlink -f -- "$BASH_SOURCE")")"; pwd)"
readonly MODULES_PATH="$CLI_PATH/modules"
readonly SRC_PATH="$CLI_PATH/src"
readonly CONFIG_PATH="$CLI_PATH/config"

source "$SRC_PATH/variables.sh"
source "$SRC_PATH/startup.sh"

#-----------------------------------------------------------
# Include Functions
#-----------------------------------------------------------

source "$SRC_PATH/functions/debug.sh"
source "$SRC_PATH/functions/depends.sh"
source "$SRC_PATH/functions/dockercompose.sh"
source "$SRC_PATH/functions/environ.sh"
source "$SRC_PATH/functions/files.sh"
source "$SRC_PATH/functions/help.sh"
source "$SRC_PATH/functions/helpers.sh"
source "$SRC_PATH/functions/input.sh"
source "$SRC_PATH/functions/logs.sh"
source "$SRC_PATH/functions/output-environ.sh"
source "$SRC_PATH/functions/output-styled.sh"
source "$SRC_PATH/functions/output-tabular.sh"
source "$SRC_PATH/functions/run.sh"
source "$SRC_PATH/functions/strings.sh"

#-----------------------------------------------------------
# Include Commands
#-----------------------------------------------------------

source "$SRC_PATH/commands/build.sh"
source "$SRC_PATH/commands/dockercompose.sh"
source "$SRC_PATH/commands/help.sh"
source "$SRC_PATH/commands/init.sh"
source "$SRC_PATH/commands/linkcli.sh"

#-----------------------------------------------------------
# Main
#-----------------------------------------------------------

main()
{
  boot
  process_arguments "$@"
  run_command
}

main "$@"
