version: '2.2'

services:

  ### Selenium Container
  selenium:
    image: laradock/selenium:local.${SELENIUM_TAG}
    build: ${BUILD_ROOT}/selenium
    ports:
      - "${SELENIUM_PORT}:4444"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - frontend
