version: '2.2'

services:

  ### Jenkins
  jenkins:
    image: laradock/jenkins:local.${JENKINS_TAG}
    build: ${JENKINS_BUILD_PATH}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "${JENKINS_HOST_SLAVE_AGENT_PORT:-50000}:50000"
      - "${JENKINS_HOST_HTTP_PORT:-8090}:8080"
    privileged: true
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - backend
