version: '2.2'

services:

  ### PHP-FPM Container
  php-fpm:
    image: laradock/php-fpm:local.${PHP_VERSION}.${PHP_FPM_TAG}
    build:
      context: ${PHP_FPM_BUILD_PATH}
      args:
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG:-false}
        - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE:-false}
        - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP:-false}
        - INSTALL_MONGO=${PHP_FPM_INSTALL_MONGO:-false}
        - INSTALL_MSSQL=${PHP_FPM_INSTALL_MSSQL:-false}
        - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE:-false}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH:-false}
        - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS:-false}
        - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED:-false}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE:-false}
        - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF:-false}
        - INSTALL_AEROSPIKE=${PHP_FPM_INSTALL_AEROSPIKE:-false}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI:-false}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER:-false}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL:-false}
        - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT:-false}
        - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP:-false}
        - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE:-false}
        - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS:-false}
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes_from:
      - applications
    volumes:
      - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    networks:
      - backend
