version: '2'

services:

  ### MSSQL Container
  mssql:
    image: laradock/mssql:local.${MSSQL_TAG}
    build:
      context: ${BUILD_ROOT}/mssql
    environment:
      - MSSQL_DATABASE=${MSSQL_DATABASE}
      - SA_PASSWORD=${MSSQL_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - ${DATA_SAVE_PATH}/mssql:/var/opt/mssql
    ports:
      - "${MSSQL_PORT}:1433"
    networks:
      - backend

volumes:
  mssql:
    driver: "local"
