version: '2.2'

services:

  ### Adminer Container
  adminer:
    image: laradock/adminer:local.${ADM_TAG}
    build:
      context: ${ADM_BUILD_PATH}
      args:
        - INSTALL_MSSQL=${ADM_INSTALL_MSSQL:-false}
    ports:
      - "${ADM_PORT:-8080}:8080"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

volumes:
  adminer:
    driver: "local"
