version: '2.2'

services:

  ### Neo4j Container
  neo4j:
    image: laradock/neo4j:local.${NEO4J_TAG}
    build: ${NEO4J_BUILD_PATH}
    ports:
      - "${NEO4J_HTTP_HOST_PORT}:7474"
      - "${NEO4J_SHELL_HOST_PORT}:1337"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}:${NEO4J_PASSWORD}
    volumes:
      - ${DATA_SAVE_PATH}/neo4j:/var/lib/neo4j/data
    networks:
      - backend

volumes:
  neo4j:
    driver: "local"
