version: '2.2'

services:

  ### RabbitMQ Container
  rabbitmq:
    image: laradock/rabbitmq:local.${RABBITMQ_TAG}
    build: ${RABBITMQ_BUILD_PATH}
    ports:
      - "${RABBITMQ_NODE_HOST_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_HTTP_HOST_PORT}:15672"
      - "${RABBITMQ_MANAGEMENT_HTTPS_HOST_PORT}:15671"
    privileged: true
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
    depends_on:
      - php-fpm
    networks:
      - backend
