version: '2.2'

services:

  ### HHVM Container
  hhvm:
    image: laradock/hhvm:local.${HHVM_TAG}
    build: ${HHVM_BUILD_PATH}
    volumes_from:
      - applications
    expose:
      - "9000"
    depends_on:
      - workspace
    networks:
      - frontend
      - backend
