version: '2.2'

services:

  ### MongoDB Container
  mongo:
    image: laradock/mongo:local.${MONGODB_TAG}
    build: ${BUILD_ROOT}/mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${DATA_SAVE_PATH}/mongo:/data/db
    networks:
      - backend

volumes:
  mongo:
    driver: "local"
