version: '2'

services:

  ### MongoDB Container
  mongo:
    build: ./mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${DATA_SAVE_PATH}/mongo:/data/db
    networks:
      - backend

volumes:
  mongo:
    driver: "local"
