version: '2'

services:

  ### pgAdmin Container
  pgadmin:
    image: laradock/pgadmin:local.${PGADMIN_TAG}
    build: ${BUILD_ROOT}/pgadmin
    ports:
      - "5050:5050"
    depends_on:
      - postgres
    networks:
      - frontend
      - backend
