version: '2.2'

services:

  ### Minio Container
  minio:
    image: laradock/minio:local.${MINIO_TAG}
    build: ${MINIO_BUILD_PATH}
    volumes:
      - ${MINIO_PATH:-minio}:/export
    ports:
      - "${MINIO_PORT:-9000}:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - frontend

volumes:
  minio:
    driver: "local"
