version: '2'

services:

  ### Redis Container
  redis:
    image: laradock/redis:local.${REDIS_TAG}
    build: ${BUILD_ROOT}/redis
    volumes:
      - ${DATA_SAVE_PATH}/redis:/data
    ports:
      - "${REDIS_HOST_PORT}:6379"
    networks:
      - backend

volumes:
  redis:
    driver: "local"
