version: '2.2'

services:

  ### Redis Container
  redis:
    image: laradock/redis:local.${REDIS_TAG}
    build: ${REDIS_BUILD_PATH}
    volumes:
      - ${DATA_SAVE_PATH}/redis:/data
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    networks:
      - backend

volumes:
  redis:
    driver: "local"
