#!/bin/sh

BASEDIR=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
SCRIPT="$SOURCE"
BASHBIN="/bin/bash"

case $(uname) in
  *CYGWIN*) BASEDIR=$(cygpath -w "$BASEDIR");;
esac

if [ -x "$BASEDIR/$BASHBIN" ]; then
  "$BASEDIR/$BASHBIN" "$BASEDIR/$SCRIPT" "$@"; RET=$?
else 
  "$BASHBIN" "$BASEDIR/$SCRIPT" "$@"; RET=$?
fi

exit $RET
