version: '2'

services:

  ### Kibana Container
  kibana:
    build: ${BUILD_ROOT}/kibana
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - frontend
      - backend
