version: '2.2'

services:

  ### Kibana Container
  kibana:
    image: laradock/kibana:local.${KIBANA_TAG}
    build: ${KIBANA_BUILD_PATH}
    ports:
      - "${KIBANA_HTTP_PORT:-5601}:5601"
    depends_on:
      - elasticsearch
    networks:
      - frontend
      - backend
