version: '2.2'

services:

  ### Workspace Utilities Container
  workspace:
    image: laradock/workspace:local.${PHP_VERSION}.${WORKSPACE_TAG}
    build:
      context: ${WORKSPACE_BUILD_PATH}
      args:
        - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG:-false}
        - INSTALL_BLACKFIRE=${INSTALL_BLACKFIRE:-false}
        - INSTALL_SOAP=${WORKSPACE_INSTALL_SOAP:-false}
        - INSTALL_MONGO=${WORKSPACE_INSTALL_MONGO:-false}
        - INSTALL_MSSQL=${WORKSPACE_INSTALL_MSSQL:-false}
        - INSTALL_NODE=${WORKSPACE_INSTALL_NODE:-false}
        - INSTALL_YARN=${WORKSPACE_INSTALL_YARN:-false}
        - INSTALL_DRUSH=${WORKSPACE_INSTALL_DRUSH:-false}
        - INSTALL_AEROSPIKE=${WORKSPACE_INSTALL_AEROSPIKE:-false}
        - INSTALL_V8JS=${WORKSPACE_INSTALL_V8JS:-false}
        - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL:-false}
        - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_WORKSPACE_SSH:-false}
        - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY:-false}
        - INSTALL_LARAVEL_INSTALLER=${WORKSPACE_INSTALL_LARAVEL_INSTALLER:-false}
        - INSTALL_DEPLOYER=${WORKSPACE_INSTALL_DEPLOYER:-false}
        - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW:-false}
        - INSTALL_MC=${WORKSPACE_INSTALL_MC:-false}
        - INSTALL_IMAGE_OPTIMIZERS=${WORKSPACE_INSTALL_IMAGE_OPTIMIZERS:-false}
        - PUID=${WORKSPACE_PUID:-1000}
        - PGID=${WORKSPACE_PGID:-1000}
        - NODE_VERSION=${WORKSPACE_NODE_VERSION:-stable}
        - YARN_VERSION=${WORKSPACE_YARN_VERSION:-latest}
        - TZ=${WORKSPACE_TIMEZONE:-UTC}
        - BLACKFIRE_CLIENT_ID=${BLACKFIRE_CLIENT_ID:-<client_id>}
        - BLACKFIRE_CLIENT_TOKEN=${BLACKFIRE_CLIENT_TOKEN:-<client_token>}
      dockerfile: "Dockerfile-${PHP_VERSION}"
    volumes_from:
      - applications
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT:-2222}:22"
    tty: true
    networks:
      - frontend
      - backend
