version: '2.2'

services:

  ### Node Container
  node:
    image: laradock/node:local.${NODE_TAG}
    build: 
      context: ${NODE_BUILD_PATH}
      args:
        - "NODE_VERSION=${NODE_VERSION:-stable}"
        - "NPM_GLOBALS=${NODE_NPM_GLOBALS}"
        - "INSTALL_YARN=${NODE_INSTALL_YARN:-false}"
        - "YARN_VERSION=${NODE_YARN_VERSION:-latest}"
    tty: true
    restart: "always"
    user: node
    working_dir: /home/node/app
    entrypoint: bash /home/node/bin/entrypoint.sh
    command: "${NODE_START_COMMAND:-npm start}"
    environment:
      - "NODE_ENV=${NODE_ENV:-production}"
      - "NPM_NO_BIN_LINKS=${NODE_NPM_NO_BIN_LINKS:-false}"
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${NODE_PORT}"
    volumes:
      - "${NODE_APP_PATH}:/home/node/app"
      - "${NODE_ENTRYPOINT_PATH}:/home/node/bin/entrypoint.sh"
      - "${NODE_MODULES_PATH}:/home/node/app/node_modules"
    networks:
      - frontend
      - backend

volumes:
  node_modules:
    driver: "local"
