version: '2'

services:

  ### Certbot Container
  certbot:
    image: laradock/certbot:local.${CERTBOT_TAG}
    build:
      context: ${BUILD_ROOT}/certbot
    volumes:
      - ./data/certbot/certs/:/var/certs
      - ./certbot/letsencrypt/:/var/www/letsencrypt
    environment:
      - CN="fake.domain.com"
      - EMAIL="fake.email@gmail.com"
    networks:
      - frontend
