version: '2.2'

services:

  ### Certbot Container
  certbot:
    image: laradock/certbot:local.${CERTBOT_TAG}
    build:
      context: ${CERTBOT_BUILD_PATH}
    volumes:
      - ${CERTBOT_CERTS_PATH}:/var/certs
      - ${CERTBOT_LETSENCRYPT_PATH}:/var/www/letsencrypt
    environment:
      - CN="${CERTBOT_DOMAIN}"
      - EMAIL="${CERTBOT_EMAIL}"
    networks:
      - frontend
