version: '2.2'

services:

  ### PHP Worker Container
  php-worker:
    image: laradock/php-worker:local.${PHP_WORKER_TAG}
    build:
      context: ${PHP_WORKER_BUILD_PATH}
    volumes_from:
      - applications
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    networks:
      - backend
