version: '2'

services:

  ### Nginx Server Container
  nginx:
    build:
      context: ${BUILD_ROOT}/nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes_from:
      - applications
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
