version: '2'

services:

  ### Laravel Echo Server
  laravel-echo-server:
    build:
      context: ${BUILD_ROOT}/laravel-echo-server
    volumes:
      - ${BUILD_ROOT}/laravel-echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
      - "${LARAVEL_ECHO_SERVER_PORT}:6001"
    links:
      - redis
    networks:
      - frontend
      - backend
