version: '2.2'

services:

  ### Laravel Echo Server
  laravel-echo-server:
    image: laradock/laravel-echo-server:local.${LARAVEL_ECHO_SERVER_TAG}
    build:
      context: ${LARAVEL_ECHO_SERVER_BUILD_PATH}
    volumes:
      - ${LARAVEL_ECHO_SERVER_CONFIG_PATH}:/app/laravel-echo-server.json:ro
    ports:
      - "${LARAVEL_ECHO_SERVER_PORT:-6001}:6001"
    links:
      - redis
    networks:
      - frontend
      - backend
