version: '2.2'

services:

  ### Beanstalkd Container
  beanstalkd:
    image: laradock/beanstalkd:local.${BEANSTALKD_TAG}
    build: ${BUILD_ROOT}/beanstalkd
    ports:
      - "${BEANSTALKD_HOST_PORT}:11300"
    privileged: true
    depends_on:
      - php-fpm
    networks:
      - backend
