version: '2.2'

services:

  ### PostgreSQL Container
  postgres:
    image: laradock/postgres:local.${POSTGRES_TAG}
    build: ${BUILD_ROOT}/postgres
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

volumes:
  postgres:
    driver: "local"
