version: '2.2'

services:

  ### PostgreSQL PostGis Container
  postgres-postgis:
    image: laradock/postgres-postgis:local.${POSTGRES_POSTGIS_TAG}
    build: ${BUILD_ROOT}/postgres-postgis
    volumes:
      - ${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
